<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Europe
            ['id' => 'ad', 'name' => ['fr' => 'Andorre', 'ar' => 'أندورا'], 'code' => 'AD'],
            ['id' => 'al', 'name' => ['fr' => 'Albanie', 'ar' => 'ألبانيا'], 'code' => 'AL'],
            ['id' => 'at', 'name' => ['fr' => 'Autriche', 'ar' => 'النمسا'], 'code' => 'AT'],
            ['id' => 'ba', 'name' => ['fr' => 'Bosnie-Herzégovine', 'ar' => 'البوسنة والهرسك'], 'code' => 'BA'],
            ['id' => 'be', 'name' => ['fr' => 'Belgique', 'ar' => 'بلجيكا'], 'code' => 'BE'],
            ['id' => 'bg', 'name' => ['fr' => 'Bulgarie', 'ar' => 'بلغاريا'], 'code' => 'BG'],
            ['id' => 'by', 'name' => ['fr' => 'Biélorussie', 'ar' => 'بيلاروسيا'], 'code' => 'BY'],
            ['id' => 'ch', 'name' => ['fr' => 'Suisse', 'ar' => 'سويسرا'], 'code' => 'CH'],
            ['id' => 'cy', 'name' => ['fr' => 'Chypre', 'ar' => 'قبرص'], 'code' => 'CY'],
            ['id' => 'cz', 'name' => ['fr' => 'République tchèque', 'ar' => 'التشيك'], 'code' => 'CZ'],
            ['id' => 'de', 'name' => ['fr' => 'Allemagne', 'ar' => 'ألمانيا'], 'code' => 'DE'],
            ['id' => 'dk', 'name' => ['fr' => 'Danemark', 'ar' => 'الدنمارك'], 'code' => 'DK'],
            ['id' => 'ee', 'name' => ['fr' => 'Estonie', 'ar' => 'إستونيا'], 'code' => 'EE'],
            ['id' => 'es', 'name' => ['fr' => 'Espagne', 'ar' => 'إسبانيا'], 'code' => 'ES'],
            ['id' => 'fi', 'name' => ['fr' => 'Finlande', 'ar' => 'فنلندا'], 'code' => 'FI'],
            ['id' => 'fr', 'name' => ['fr' => 'France', 'ar' => 'فرنسا'], 'code' => 'FR'],
            ['id' => 'gb', 'name' => ['fr' => 'Royaume-Uni', 'ar' => 'المملكة المتحدة'], 'code' => 'GB'],
            ['id' => 'gr', 'name' => ['fr' => 'Grèce', 'ar' => 'اليونان'], 'code' => 'GR'],
            ['id' => 'hr', 'name' => ['fr' => 'Croatie', 'ar' => 'كرواتيا'], 'code' => 'HR'],
            ['id' => 'hu', 'name' => ['fr' => 'Hongrie', 'ar' => 'المجر'], 'code' => 'HU'],
            ['id' => 'ie', 'name' => ['fr' => 'Irlande', 'ar' => 'أيرلندا'], 'code' => 'IE'],
            ['id' => 'is', 'name' => ['fr' => 'Islande', 'ar' => 'أيسلندا'], 'code' => 'IS'],
            ['id' => 'it', 'name' => ['fr' => 'Italie', 'ar' => 'إيطاليا'], 'code' => 'IT'],
            ['id' => 'li', 'name' => ['fr' => 'Liechtenstein', 'ar' => 'ليختنشتاين'], 'code' => 'LI'],
            ['id' => 'lt', 'name' => ['fr' => 'Lituanie', 'ar' => 'ليتوانيا'], 'code' => 'LT'],
            ['id' => 'lu', 'name' => ['fr' => 'Luxembourg', 'ar' => 'لوكسمبورغ'], 'code' => 'LU'],
            ['id' => 'lv', 'name' => ['fr' => 'Lettonie', 'ar' => 'لاتفيا'], 'code' => 'LV'],
            ['id' => 'mc', 'name' => ['fr' => 'Monaco', 'ar' => 'موناكو'], 'code' => 'MC'],
            ['id' => 'md', 'name' => ['fr' => 'Moldavie', 'ar' => 'مولدوفا'], 'code' => 'MD'],
            ['id' => 'me', 'name' => ['fr' => 'Monténégro', 'ar' => 'الجبل الأسود'], 'code' => 'ME'],
            ['id' => 'mk', 'name' => ['fr' => 'Macédoine du Nord', 'ar' => 'مقدونيا الشمالية'], 'code' => 'MK'],
            ['id' => 'mt', 'name' => ['fr' => 'Malte', 'ar' => 'مالطا'], 'code' => 'MT'],
            ['id' => 'nl', 'name' => ['fr' => 'Pays-Bas', 'ar' => 'هولندا'], 'code' => 'NL'],
            ['id' => 'no', 'name' => ['fr' => 'Norvège', 'ar' => 'النرويج'], 'code' => 'NO'],
            ['id' => 'pl', 'name' => ['fr' => 'Pologne', 'ar' => 'بولندا'], 'code' => 'PL'],
            ['id' => 'pt', 'name' => ['fr' => 'Portugal', 'ar' => 'البرتغال'], 'code' => 'PT'],
            ['id' => 'ro', 'name' => ['fr' => 'Roumanie', 'ar' => 'رومانيا'], 'code' => 'RO'],
            ['id' => 'rs', 'name' => ['fr' => 'Serbie', 'ar' => 'صربيا'], 'code' => 'RS'],
            ['id' => 'ru', 'name' => ['fr' => 'Russie', 'ar' => 'روسيا'], 'code' => 'RU'],
            ['id' => 'se', 'name' => ['fr' => 'Suède', 'ar' => 'السويد'], 'code' => 'SE'],
            ['id' => 'si', 'name' => ['fr' => 'Slovénie', 'ar' => 'سلوفينيا'], 'code' => 'SI'],
            ['id' => 'sk', 'name' => ['fr' => 'Slovaquie', 'ar' => 'سلوفاكيا'], 'code' => 'SK'],
            ['id' => 'sm', 'name' => ['fr' => 'Saint-Marin', 'ar' => 'سان مارينو'], 'code' => 'SM'],
            ['id' => 'ua', 'name' => ['fr' => 'Ukraine', 'ar' => 'أوكرانيا'], 'code' => 'UA'],
            ['id' => 'va', 'name' => ['fr' => 'Vatican', 'ar' => 'الفاتيكان'], 'code' => 'VA'],
            ['id' => 'xk', 'name' => ['fr' => 'Kosovo', 'ar' => 'كوسوفو'], 'code' => 'XK'],

            // Asie
            ['id' => 'af', 'name' => ['fr' => 'Afghanistan', 'ar' => 'أفغانستان'], 'code' => 'AF'],
            ['id' => 'am', 'name' => ['fr' => 'Arménie', 'ar' => 'أرمينيا'], 'code' => 'AM'],
            ['id' => 'az', 'name' => ['fr' => 'Azerbaïdjan', 'ar' => 'أذربيجان'], 'code' => 'AZ'],
            ['id' => 'bd', 'name' => ['fr' => 'Bangladesh', 'ar' => 'بنغلاديش'], 'code' => 'BD'],
            ['id' => 'bh', 'name' => ['fr' => 'Bahreïn', 'ar' => 'البحرين'], 'code' => 'BH'],
            ['id' => 'bn', 'name' => ['fr' => 'Brunei', 'ar' => 'بروناي'], 'code' => 'BN'],
            ['id' => 'bt', 'name' => ['fr' => 'Bhoutan', 'ar' => 'بوتان'], 'code' => 'BT'],
            ['id' => 'cn', 'name' => ['fr' => 'Chine', 'ar' => 'الصين'], 'code' => 'CN'],
            ['id' => 'ge', 'name' => ['fr' => 'Géorgie', 'ar' => 'جورجيا'], 'code' => 'GE'],
            ['id' => 'id', 'name' => ['fr' => 'Indonésie', 'ar' => 'إندونيسيا'], 'code' => 'ID'],
            ['id' => 'il', 'name' => ['fr' => 'Israël', 'ar' => 'إسرائيل'], 'code' => 'IL'],
            ['id' => 'in', 'name' => ['fr' => 'Inde', 'ar' => 'الهند'], 'code' => 'IN'],
            ['id' => 'iq', 'name' => ['fr' => 'Irak', 'ar' => 'العراق'], 'code' => 'IQ'],
            ['id' => 'ir', 'name' => ['fr' => 'Iran', 'ar' => 'إيران'], 'code' => 'IR'],
            ['id' => 'jo', 'name' => ['fr' => 'Jordanie', 'ar' => 'الأردن'], 'code' => 'JO'],
            ['id' => 'jp', 'name' => ['fr' => 'Japon', 'ar' => 'اليابان'], 'code' => 'JP'],
            ['id' => 'kg', 'name' => ['fr' => 'Kirghizistan', 'ar' => 'قيرغيزستان'], 'code' => 'KG'],
            ['id' => 'kh', 'name' => ['fr' => 'Cambodge', 'ar' => 'كمبوديا'], 'code' => 'KH'],
            ['id' => 'kp', 'name' => ['fr' => 'Corée du Nord', 'ar' => 'كوريا الشمالية'], 'code' => 'KP'],
            ['id' => 'kr', 'name' => ['fr' => 'Corée du Sud', 'ar' => 'كوريا الجنوبية'], 'code' => 'KR'],
            ['id' => 'kw', 'name' => ['fr' => 'Koweït', 'ar' => 'الكويت'], 'code' => 'KW'],
            ['id' => 'kz', 'name' => ['fr' => 'Kazakhstan', 'ar' => 'كازاخستان'], 'code' => 'KZ'],
            ['id' => 'la', 'name' => ['fr' => 'Laos', 'ar' => 'لاوس'], 'code' => 'LA'],
            ['id' => 'lb', 'name' => ['fr' => 'Liban', 'ar' => 'لبنان'], 'code' => 'LB'],
            ['id' => 'lk', 'name' => ['fr' => 'Sri Lanka', 'ar' => 'سريلانكا'], 'code' => 'LK'],
            ['id' => 'mm', 'name' => ['fr' => 'Myanmar', 'ar' => 'ميانمار'], 'code' => 'MM'],
            ['id' => 'mn', 'name' => ['fr' => 'Mongolie', 'ar' => 'منغوليا'], 'code' => 'MN'],
            ['id' => 'mv', 'name' => ['fr' => 'Maldives', 'ar' => 'المالديف'], 'code' => 'MV'],
            ['id' => 'my', 'name' => ['fr' => 'Malaisie', 'ar' => 'ماليزيا'], 'code' => 'MY'],
            ['id' => 'np', 'name' => ['fr' => 'Népal', 'ar' => 'نيبال'], 'code' => 'NP'],
            ['id' => 'om', 'name' => ['fr' => 'Oman', 'ar' => 'عُمان'], 'code' => 'OM'],
            ['id' => 'ph', 'name' => ['fr' => 'Philippines', 'ar' => 'الفلبين'], 'code' => 'PH'],
            ['id' => 'pk', 'name' => ['fr' => 'Pakistan', 'ar' => 'باكستان'], 'code' => 'PK'],
            ['id' => 'ps', 'name' => ['fr' => 'Palestine', 'ar' => 'فلسطين'], 'code' => 'PS'],
            ['id' => 'qa', 'name' => ['fr' => 'Qatar', 'ar' => 'قطر'], 'code' => 'QA'],
            ['id' => 'sa', 'name' => ['fr' => 'Arabie Saoudite', 'ar' => 'المملكة العربية السعودية'], 'code' => 'SA'],
            ['id' => 'sg', 'name' => ['fr' => 'Singapour', 'ar' => 'سنغافورة'], 'code' => 'SG'],
            ['id' => 'sy', 'name' => ['fr' => 'Syrie', 'ar' => 'سوريا'], 'code' => 'SY'],
            ['id' => 'th', 'name' => ['fr' => 'Thaïlande', 'ar' => 'تايلاند'], 'code' => 'TH'],
            ['id' => 'tj', 'name' => ['fr' => 'Tadjikistan', 'ar' => 'طاجيكستان'], 'code' => 'TJ'],
            ['id' => 'tm', 'name' => ['fr' => 'Turkménistan', 'ar' => 'تركمانستان'], 'code' => 'TM'],
            ['id' => 'tr', 'name' => ['fr' => 'Turquie', 'ar' => 'تركيا'], 'code' => 'TR'],
            ['id' => 'tw', 'name' => ['fr' => 'Taïwan', 'ar' => 'تايوان'], 'code' => 'TW'],
            ['id' => 'uz', 'name' => ['fr' => 'Ouzbékistan', 'ar' => 'أوزبكستان'], 'code' => 'UZ'],
            ['id' => 'vn', 'name' => ['fr' => 'Vietnam', 'ar' => 'فيتنام'], 'code' => 'VN'],
            ['id' => 'ye', 'name' => ['fr' => 'Yémen', 'ar' => 'اليمن'], 'code' => 'YE'],

            // Afrique
            ['id' => 'ao', 'name' => ['fr' => 'Angola', 'ar' => 'أنغولا'], 'code' => 'AO'],
            ['id' => 'bf', 'name' => ['fr' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'], 'code' => 'BF'],
            ['id' => 'bi', 'name' => ['fr' => 'Burundi', 'ar' => 'بوروندي'], 'code' => 'BI'],
            ['id' => 'bj', 'name' => ['fr' => 'Bénin', 'ar' => 'بنين'], 'code' => 'BJ'],
            ['id' => 'bw', 'name' => ['fr' => 'Botswana', 'ar' => 'بوتسوانا'], 'code' => 'BW'],
            ['id' => 'cd', 'name' => ['fr' => 'République démocratique du Congo', 'ar' => 'جمهورية الكونغو الديمقراطية'], 'code' => 'CD'],
            ['id' => 'cf', 'name' => ['fr' => 'République centrafricaine', 'ar' => 'جمهورية أفريقيا الوسطى'], 'code' => 'CF'],
            ['id' => 'cg', 'name' => ['fr' => 'République du Congo', 'ar' => 'جمهورية الكونغو'], 'code' => 'CG'],
            ['id' => 'ci', 'name' => ['fr' => 'Côte d\'Ivoire', 'ar' => 'ساحل العاج'], 'code' => 'CI'],
            ['id' => 'cm', 'name' => ['fr' => 'Cameroun', 'ar' => 'الكاميرون'], 'code' => 'CM'],
            ['id' => 'cv', 'name' => ['fr' => 'Cap-Vert', 'ar' => 'الرأس الأخضر'], 'code' => 'CV'],
            ['id' => 'dj', 'name' => ['fr' => 'Djibouti', 'ar' => 'جيبوتي'], 'code' => 'DJ'],
            ['id' => 'dz', 'name' => ['fr' => 'Algérie', 'ar' => 'الجزائر'], 'code' => 'DZ'],
            ['id' => 'eg', 'name' => ['fr' => 'Égypte', 'ar' => 'مصر'], 'code' => 'EG'],
            ['id' => 'eh', 'name' => ['fr' => 'Sahara occidental', 'ar' => 'الصحراء الغربية'], 'code' => 'EH'],
            ['id' => 'er', 'name' => ['fr' => 'Érythrée', 'ar' => 'إريتريا'], 'code' => 'ER'],
            ['id' => 'et', 'name' => ['fr' => 'Éthiopie', 'ar' => 'إثيوبيا'], 'code' => 'ET'],
            ['id' => 'ga', 'name' => ['fr' => 'Gabon', 'ar' => 'الغابون'], 'code' => 'GA'],
            ['id' => 'gh', 'name' => ['fr' => 'Ghana', 'ar' => 'غانا'], 'code' => 'GH'],
            ['id' => 'gm', 'name' => ['fr' => 'Gambie', 'ar' => 'غامبيا'], 'code' => 'GM'],
            ['id' => 'gn', 'name' => ['fr' => 'Guinée', 'ar' => 'غينيا'], 'code' => 'GN'],
            ['id' => 'gq', 'name' => ['fr' => 'Guinée équatoriale', 'ar' => 'غينيا الاستوائية'], 'code' => 'GQ'],
            ['id' => 'gw', 'name' => ['fr' => 'Guinée-Bissau', 'ar' => 'غينيا بيساو'], 'code' => 'GW'],
            ['id' => 'ke', 'name' => ['fr' => 'Kenya', 'ar' => 'كينيا'], 'code' => 'KE'],
            ['id' => 'km', 'name' => ['fr' => 'Comores', 'ar' => 'جزر القمر'], 'code' => 'KM'],
            ['id' => 'lr', 'name' => ['fr' => 'Libéria', 'ar' => 'ليبيريا'], 'code' => 'LR'],
            ['id' => 'ls', 'name' => ['fr' => 'Lesotho', 'ar' => 'ليسوتو'], 'code' => 'LS'],
            ['id' => 'ly', 'name' => ['fr' => 'Libye', 'ar' => 'ليبيا'], 'code' => 'LY'],
            ['id' => 'ma', 'name' => ['fr' => 'Maroc', 'ar' => 'المغرب'], 'code' => 'MA'],
            ['id' => 'mg', 'name' => ['fr' => 'Madagascar', 'ar' => 'مدغشقر'], 'code' => 'MG'],
            ['id' => 'ml', 'name' => ['fr' => 'Mali', 'ar' => 'مالي'], 'code' => 'ML'],
            ['id' => 'mr', 'name' => ['fr' => 'Mauritanie', 'ar' => 'موريتانيا'], 'code' => 'MR'],
            ['id' => 'mu', 'name' => ['fr' => 'Maurice', 'ar' => 'موريشيوس'], 'code' => 'MU'],
            ['id' => 'mw', 'name' => ['fr' => 'Malawi', 'ar' => 'مالاوي'], 'code' => 'MW'],
            ['id' => 'mz', 'name' => ['fr' => 'Mozambique', 'ar' => 'موزمبيق'], 'code' => 'MZ'],
            ['id' => 'na', 'name' => ['fr' => 'Namibie', 'ar' => 'ناميبيا'], 'code' => 'NA'],
            ['id' => 'ne', 'name' => ['fr' => 'Niger', 'ar' => 'النيجر'], 'code' => 'NE'],
            ['id' => 'ng', 'name' => ['fr' => 'Nigéria', 'ar' => 'نيجيريا'], 'code' => 'NG'],
            ['id' => 'rw', 'name' => ['fr' => 'Rwanda', 'ar' => 'رواندا'], 'code' => 'RW'],
            ['id' => 'sc', 'name' => ['fr' => 'Seychelles', 'ar' => 'سيشل'], 'code' => 'SC'],
            ['id' => 'sd', 'name' => ['fr' => 'Soudan', 'ar' => 'السودان'], 'code' => 'SD'],
            ['id' => 'sl', 'name' => ['fr' => 'Sierra Leone', 'ar' => 'سيراليون'], 'code' => 'SL'],
            ['id' => 'sn', 'name' => ['fr' => 'Sénégal', 'ar' => 'السنغال'], 'code' => 'SN'],
            ['id' => 'so', 'name' => ['fr' => 'Somalie', 'ar' => 'الصومال'], 'code' => 'SO'],
            ['id' => 'ss', 'name' => ['fr' => 'Soudan du Sud', 'ar' => 'جنوب السودان'], 'code' => 'SS'],
            ['id' => 'st', 'name' => ['fr' => 'Sao Tomé-et-Principe', 'ar' => 'ساو تومي وبرينسيبي'], 'code' => 'ST'],
            ['id' => 'sz', 'name' => ['fr' => 'Eswatini', 'ar' => 'إسواتيني'], 'code' => 'SZ'],
            ['id' => 'td', 'name' => ['fr' => 'Tchad', 'ar' => 'تشاد'], 'code' => 'TD'],
            ['id' => 'tg', 'name' => ['fr' => 'Togo', 'ar' => 'توغو'], 'code' => 'TG'],
            ['id' => 'tn', 'name' => ['fr' => 'Tunisie', 'ar' => 'تونس'], 'code' => 'TN'],
            ['id' => 'tz', 'name' => ['fr' => 'Tanzanie', 'ar' => 'تنزانيا'], 'code' => 'TZ'],
            ['id' => 'ug', 'name' => ['fr' => 'Ouganda', 'ar' => 'أوغندا'], 'code' => 'UG'],
            ['id' => 'za', 'name' => ['fr' => 'Afrique du Sud', 'ar' => 'جنوب أفريقيا'], 'code' => 'ZA'],
            ['id' => 'zm', 'name' => ['fr' => 'Zambie', 'ar' => 'زامبيا'], 'code' => 'ZM'],
            ['id' => 'zw', 'name' => ['fr' => 'Zimbabwe', 'ar' => 'زيمبابوي'], 'code' => 'ZW'],

            // Amérique du Nord
            ['id' => 'ag', 'name' => ['fr' => 'Antigua-et-Barbuda', 'ar' => 'أنتيغوا وبربودا'], 'code' => 'AG'],
            ['id' => 'bb', 'name' => ['fr' => 'Barbade', 'ar' => 'بربادوس'], 'code' => 'BB'],
            ['id' => 'bs', 'name' => ['fr' => 'Bahamas', 'ar' => 'البهاما'], 'code' => 'BS'],
            ['id' => 'bz', 'name' => ['fr' => 'Belize', 'ar' => 'بليز'], 'code' => 'BZ'],
            ['id' => 'ca', 'name' => ['fr' => 'Canada', 'ar' => 'كندا'], 'code' => 'CA'],
            ['id' => 'cr', 'name' => ['fr' => 'Costa Rica', 'ar' => 'كوستاريكا'], 'code' => 'CR'],
            ['id' => 'cu', 'name' => ['fr' => 'Cuba', 'ar' => 'كوبا'], 'code' => 'CU'],
            ['id' => 'dm', 'name' => ['fr' => 'Dominique', 'ar' => 'دومينيكا'], 'code' => 'DM'],
            ['id' => 'do', 'name' => ['fr' => 'République dominicaine', 'ar' => 'جمهورية الدومينيكان'], 'code' => 'DO'],
            ['id' => 'gd', 'name' => ['fr' => 'Grenade', 'ar' => 'غرينادا'], 'code' => 'GD'],
            ['id' => 'gt', 'name' => ['fr' => 'Guatemala', 'ar' => 'غواتيمالا'], 'code' => 'GT'],
            ['id' => 'hn', 'name' => ['fr' => 'Honduras', 'ar' => 'هندوراس'], 'code' => 'HN'],
            ['id' => 'ht', 'name' => ['fr' => 'Haïti', 'ar' => 'هايتي'], 'code' => 'HT'],
            ['id' => 'jm', 'name' => ['fr' => 'Jamaïque', 'ar' => 'جامايكا'], 'code' => 'JM'],
            ['id' => 'kn', 'name' => ['fr' => 'Saint-Christophe-et-Niévès', 'ar' => 'سانت كيتس ونيفيس'], 'code' => 'KN'],
            ['id' => 'lc', 'name' => ['fr' => 'Sainte-Lucie', 'ar' => 'سانت لوسيا'], 'code' => 'LC'],
            ['id' => 'mx', 'name' => ['fr' => 'Mexique', 'ar' => 'المكسيك'], 'code' => 'MX'],
            ['id' => 'ni', 'name' => ['fr' => 'Nicaragua', 'ar' => 'نيكاراغوا'], 'code' => 'NI'],
            ['id' => 'pa', 'name' => ['fr' => 'Panama', 'ar' => 'بنما'], 'code' => 'PA'],
            ['id' => 'sv', 'name' => ['fr' => 'Salvador', 'ar' => 'السلفادور'], 'code' => 'SV'],
            ['id' => 'tt', 'name' => ['fr' => 'Trinité-et-Tobago', 'ar' => 'ترينيداد وتوباغو'], 'code' => 'TT'],
            ['id' => 'us', 'name' => ['fr' => 'États-Unis', 'ar' => 'الولايات المتحدة'], 'code' => 'US'],
            ['id' => 'vc', 'name' => ['fr' => 'Saint-Vincent-et-les-Grenadines', 'ar' => 'سانت فنسنت وجزر غرينادين'], 'code' => 'VC'],

            // Amérique du Sud
            ['id' => 'ar', 'name' => ['fr' => 'Argentine', 'ar' => 'الأرجنتين'], 'code' => 'AR'],
            ['id' => 'bo', 'name' => ['fr' => 'Bolivie', 'ar' => 'بوليفيا'], 'code' => 'BO'],
            ['id' => 'br', 'name' => ['fr' => 'Brésil', 'ar' => 'البرازيل'], 'code' => 'BR'],
            ['id' => 'cl', 'name' => ['fr' => 'Chili', 'ar' => 'تشيلي'], 'code' => 'CL'],
            ['id' => 'co', 'name' => ['fr' => 'Colombie', 'ar' => 'كولومبيا'], 'code' => 'CO'],
            ['id' => 'ec', 'name' => ['fr' => 'Équateur', 'ar' => 'الإكوادور'], 'code' => 'EC'],
            ['id' => 'gy', 'name' => ['fr' => 'Guyana', 'ar' => 'غيانا'], 'code' => 'GY'],
            ['id' => 'pe', 'name' => ['fr' => 'Pérou', 'ar' => 'بيرو'], 'code' => 'PE'],
            ['id' => 'py', 'name' => ['fr' => 'Paraguay', 'ar' => 'باراغواي'], 'code' => 'PY'],
            ['id' => 'sr', 'name' => ['fr' => 'Suriname', 'ar' => 'سورينام'], 'code' => 'SR'],
            ['id' => 'uy', 'name' => ['fr' => 'Uruguay', 'ar' => 'أوروغواي'], 'code' => 'UY'],
            ['id' => 've', 'name' => ['fr' => 'Venezuela', 'ar' => 'فنزويلا'], 'code' => 'VE'],

            // Océanie
            ['id' => 'au', 'name' => ['fr' => 'Australie', 'ar' => 'أستراليا'], 'code' => 'AU'],
            ['id' => 'fj', 'name' => ['fr' => 'Fidji', 'ar' => 'فيجي'], 'code' => 'FJ'],
            ['id' => 'ki', 'name' => ['fr' => 'Kiribati', 'ar' => 'كيريباس'], 'code' => 'KI'],
            ['id' => 'mh', 'name' => ['fr' => 'Îles Marshall', 'ar' => 'جزر مارشال'], 'code' => 'MH'],
            ['id' => 'fm', 'name' => ['fr' => 'Micronésie', 'ar' => 'ميكرونيزيا'], 'code' => 'FM'],
            ['id' => 'nr', 'name' => ['fr' => 'Nauru', 'ar' => 'ناورو'], 'code' => 'NR'],
            ['id' => 'nz', 'name' => ['fr' => 'Nouvelle-Zélande', 'ar' => 'نيوزيلندا'], 'code' => 'NZ'],
            ['id' => 'pw', 'name' => ['fr' => 'Palaos', 'ar' => 'بالاو'], 'code' => 'PW'],
            ['id' => 'pg', 'name' => ['fr' => 'Papouasie-Nouvelle-Guinée', 'ar' => 'بابوا غينيا الجديدة'], 'code' => 'PG'],
            ['id' => 'ws', 'name' => ['fr' => 'Samoa', 'ar' => 'ساموا'], 'code' => 'WS'],
            ['id' => 'sb', 'name' => ['fr' => 'Îles Salomon', 'ar' => 'جزر سليمان'], 'code' => 'SB'],
            ['id' => 'to', 'name' => ['fr' => 'Tonga', 'ar' => 'تونغا'], 'code' => 'TO'],
            ['id' => 'tv', 'name' => ['fr' => 'Tuvalu', 'ar' => 'توفالو'], 'code' => 'TV'],
            ['id' => 'vu', 'name' => ['fr' => 'Vanuatu', 'ar' => 'فانواتو'], 'code' => 'VU'],

            // Pays des Émirats arabes unis
            ['id' => 'ae', 'name' => ['fr' => 'Émirats arabes unis', 'ar' => 'الإمارات العربية المتحدة'], 'code' => 'AE'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::updateOrCreate(
                ['id' => $country['id']],
                $country
            );
        }
    }
}
