<?php

return [
    'company' => [
        'name' => 'COMMERCIAL BANK TCHAD',
        'address' => 'BP: 19 N\'DJAMENA',
        'street' => 'Rue Col.Hassan Moursal K.',
        'tel' => '22522829',
        'logo' => public_path('images/company_logo.png'),
    ],
    'labels' => [
        'period' => 'Période du',
        'payment_date' => 'Paiement le',
        'payment_mode' => 'Mode de paiement',
        'employee' => 'EMPLOYE',
        'department' => 'Département',
        'base_salary' => 'Salaire de base',
        'hourly' => 'Horaire',
        'family_status' => 'Statut familial',
        'children' => 'Nbre d\'enfants',
        'parts' => 'Nbre de Parts',
        'hired' => 'Embauche',
        'leave' => 'Congés',
        'acquired' => 'Acquis',
        'taken' => 'Pris',
        'remaining' => 'Restant',
        'pay_slip' => 'BULLETIN DE PAIE',
        'net_to_pay' => 'NET A PAYER',
        'total_gains' => 'TOTAL GAINS',
        'total_deductions' => 'TOTAL RETENUES',
        'cumulated' => 'CUMUL',
        'annual' => 'An.',
        'total_working_hours' => 'Heures de travail totales',
        'actual_working_hours' => 'Heures de travail effectuées',
        'working_hours' => 'Heures de travail',
    ],
    'columns' => [
        'number' => 'N°',
        'designation' => 'Désignation',
        'base' => 'Base',
        'rate' => 'Taux',
        'gross' => 'Brut',
        'retained' => 'Retenue',
        'employer_share' => 'Part patronale',
        'employee_share' => 'Part salariale',
    ],
];
